version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Đường dẫn đến nơi chứa file build.gradle
    schedule:
      interval: "weekly" # Dependabot sẽ kiểm tra cập nhật mỗi tuần