name: Gradle Build Workflow

on:
  workflow_dispatch: # Cho phép kích hoạt thủ công từ tab Actions
  push:
    branches:
      - main # Chạy workflow khi có thay đổi ở nhánh main
  pull_request:
    branches:
      - main # Chạy workflow khi có pull request đến nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Bước 2: Thiết lập JDK (Java 17 thường được sử dụng cho Minecraft plugins)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Bước 3: Tải Gradle Wrapper (nếu chưa có trong repo)
    - name: Ensure Gradle Wrapper
      run: |
        if [ ! -f ./gradlew ]; then
          echo "Gradle Wrapper not found. Generating wrapper..."
          gradle wrapper
        fi
        chmod +x ./gradlew

    # Bước 4: Cache dependencies của Gradle để tăng tốc độ build
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Bước 5: Build project bằng Gradle
    - name: Build project
      run: ./gradlew build

    # Bước 6: Upload file JAR được build
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-plugin
        path: build/libs/*.jar