name: Gradle Build Workflow

on:
  workflow_dispatch: # Cho phép kích hoạt thủ công từ tab Actions
  push:
    branches:
      - main # Chạy workflow khi có thay đổi ở nhánh main
  pull_request:
    branches:
      - main # Chạy workflow khi có pull request đến nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Bước 2: Thiết lập JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Bước 3: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Bước 4: Build project bằng Gradle
    - name: Build project
      run: ./gradlew build

    # Bước 5: Upload file JAR artifact
    - name: Upload built JAR file
      uses: actions/upload-artifact@v2
      with:
        name: built-plugin
        path: build/libs/*.jar